#void centTriggerTurnOn
#        const char* fname="root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIMinimumBias2/Merged/HIMinimumBias2_run262811.root",
#        const char* type="Run262811_PrivateReco" 

################ 262XXX #################
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262656.root", "Run262656_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262694.root", "Run262694_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262695.root", "Run262695_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262697.root", "Run262697_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262703.root", "Run262703_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262726.root", "Run262726_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262735.root", "Run262735_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262768.root", "Run262768_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262777.root", "Run262777_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262783.root", "Run262783_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262784.root", "Run262784_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262811.root", "Run262811_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262815.root", "Run262815_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262816.root", "Run262816_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262817.root", "Run262817_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262818.root", "Run262818_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262819.root", "Run262819_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262834.root", "Run262834_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262836.root", "Run262836_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run262837_preHBHE.root", "Run262837_Express")'

################ 263XXX #################
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263035.root", "Run263035_Express")'
################## from here, change from HF1_AND to HF2_AND for 30-100,50-100
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263212.root", "Run263212_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263213.root", "Run263213_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263233.root", "Run263233_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263234.root", "Run263234_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263261.root", "Run263261_Express")'
############### from 2015/12/07 #########
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263284.root", "Run263284_Express")'
#( sample problem ) root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263286.root", "Run263286_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263293.root", "Run263293_Express")'
#( sample problem )root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263322.root", "Run263322_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263333.root", "Run263333_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263349.root", "Run263349_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263355.root", "Run263355_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263356.root", "Run263356_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263357.root", "Run263357_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263358.root", "Run263358_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263359.root", "Run263359_Express")'
#root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263362.root", "Run263362_Express")'


root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263379.root", "Run263379_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263400.root", "Run263400_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263406.root", "Run263406_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263410.root", "Run263410_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263412.root", "Run263412_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263491.root", "Run263491_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263502.root", "Run263502_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263511.root", "Run263511_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263584.root", "Run263584_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263604.root", "Run263604_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263614.root", "Run263614_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263685.root", "Run263685_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263689.root", "Run263689_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263718.root", "Run263718_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263728.root", "Run263728_Express")'
root -l -b -q 'centTriggerTurnOn.C+("root://eoscms//eos/cms//store/group/phys_heavyions/velicanu/forest/HIRun2015/HIExpressPhysics/Merged/HIForestExpress_run263729.root", "Run263729_Express")'
